.PHONY: hello

GCC = gcc -std=c99 -pedantic -Wall -O3

rhello:
	$(GCC) hello.c -o hello
	./hello

chello:
	$(GCC) hello.c -o hello

rsquare:
	$(GCC) square.c -o square
	./square

csquare:
	$(GCC) square.c -o square

rinterest:
	$(GCC) interest.c -o interest
	./interest

cinterest:
	$(GCC) interest.c -o interest

rlimits:
	$(GCC) limits.c -o limits
	./limits

climits:
	$(GCC) limits.c -o limits
