GCC = gcc -std=c99 -pedantic -Wall -O3

rrev: reverse.c
	$(GCC) reverse.c -o rev
	./rev

crev: reverse.c
	$(GCC) reverse.c -o rev

rup: upper.c
	$(GCC) upper.c -o up
	./up

cup: upper.c
	$(GCC) upper.c -o up

rhex: hex.c
	$(GCC) hex.c -o hex
	./hex

chex: hex.c
	$(GCC) hex.c -o hex
