GCC = gcc -std=c99 -pedantic -Wall -O3

cgrade: grade.c
	$(GCC) grade.c -o grade

cegrade: gradeExtended.c
	$(GCC) gradeExtended.c -o egrade

cttt: tictactoe.c
	$(GCC) tictactoe.c -o ttt

rttt: tictactoe.c
	$(GCC) tictactoe.c -o ttt
	./ttt
