GCC = gcc -std=c99 -pedantic -Wall -O3

ctri: triangle.c
	$(GCC) triangle.c -o triangle

rtri: triangle.c
	$(GCC) triangle.c -o triangle
	./triangle

csort: sort.c
	$(GCC) sort.c -o sort

rsort: sort.c
	$(GCC) sort.c -o sort
	./sort 10 65 7 8 14 9
